POST http://localhost:3000/textbook
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFsaWNlIiwiaWF0IjoxNzEwMTM2MjgzLCJleHAiOjE3MTAyMjI2ODN9.-SwrAHL2KytGrUuYHk_RwsNMXeeS9Ei75VPsTgfJ034

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "Alice",
  "password": "password123"
}
